services:
  postgres:
    env_file: .env
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - app-network
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
    driver: local

networks:
  app-network:
    driver: bridge